-- 产品类型 建表SQL
-- 生成时间: 2026-02-10 22:34:58
-- 模块: product_type

CREATE TABLE IF NOT EXISTS `product_type` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` VARCHAR(255) NULL COMMENT '产品类型名称',
  `icon` VARCHAR(255) NULL COMMENT '类型图标',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='产品类型';
