server:
  port: 8080
  mode: test # debug, release, test
  host: 0.0.0.0:8080
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  dbname: go_rbac_admin
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100

redis:
  host: 127.0.0.1
  port: 6379
  password: "123456"
  db: 1

jwt:
  secret: go-base-server-jwt-secret-key
  expires: 7200       # token过期时间(秒) 2小时
  issuer: go-base-server

casbin:
  model_path: ./rbac_model.conf

log:
  level: info
  format: console   # console, json
  directory: ./logs

ai:
  default_provider: "阿里云百炼"  # 默认平台名称
  providers:
    - name: "阿里云百炼"
      api_key: "sk-93a09f74fb7e49dc951d8b30b06e5a04"
      base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
      models:
        - id: "deepseek-v3.2"
          name: "DeepSeek-V3.2"
          description: "DeepSeek最新模型,支持联网和思考"
        - id: "kimi-k2-thinking"
          name: "kimi-k2-thinking"
          description: "kimi-k2-thinking模型是月之暗面提供的具有通用 Agentic能力和推理能力的思考模型，它擅长深度推理，并可通过多步工具调用，帮助解决各类难题"
        - id: "glm-4.7"
          name: "GLM 4.7"
          description: "智谱最新旗舰，具备更强的编程能力与更稳定的多步骤推理/执行能力。总参数355B，支持长程任务规划、编码、工具协同，问答自然、写作沉浸、创意角色扮演能力强"
        - id: "qwen3-max-2026-01-23"
          name: "通义千问3-Max"
          description: "通义千问3系列Max模型，相较2025年9月23日快照，此版本实现思考模式和非思考模式的有效融合，模型整体效果得到全方位的大幅度提升。在思考模式下，同时发布Web搜索、Web信息提取和代码解释器工具能力，使得模型在慢思考的同时，能够通过引入外部工具，以更高的准确性解决更有难度的问题。此版本为2026年1月23日快照"

    - name: "ModelScope 魔搭"
      api_key: "ms-acb27b8a-bf0b-4f8e-b66e-c3f356448088"
      base_url: "https://api-inference.modelscope.cn/v1"
      models:
        - id: "Qwen/Qwen3-235B-A22B-Thinking-2507"
          name: "Qwen/Qwen3-235B-A22B-Thinking-2507"
          description: ""
        - id: "Qwen/Qwen3-235B-A22B"
          name: "Qwen/Qwen3-235B-A22B"
          description: ""
        - id: "deepseek-ai/DeepSeek-V3.2"
          name: "deepseek-ai/DeepSeek-V3.2"
          description: ""
        - id: "ZhipuAI/GLM-4.7"
          name: "ZhipuAI/GLM-4.7"
          description: ""
