server:
  port: 8080
  mode: test # debug, release, test
  host: 0.0.0.0:8080
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  dbname: go_rbac_admin
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100

redis:
  host: 127.0.0.1
  port: 6379
  password: "123456"
  db: 1

jwt:
  secret: server-jwt-secret-key
  expires: 7200       # token过期时间(秒) 2小时
  issuer: server

casbin:
  model_path: ./rbac_model.conf

log:
  level: info
  format: console   # console, json
  directory: ./logs


