server:
  port: 8080
  mode: debug  # debug, release, test
  host: localhost:8080
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  dbname: go-base
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100

redis:
  host: 127.0.0.1
  port: 6379
  password: "123456"
  db: 1

jwt:
  secret: go-base-jwt-secret-key
  expires: 7200          # token过期时间(秒) 2小时
  refresh_window: 604800 # 过期后允许刷新的时间窗口(秒) 7天
  issuer: web

casbin:
  model_path: ./rbac_model.conf

log:
  level: info
  format: console   # console, json
  directory: ./logs

